// Sumas para las cards del dashboard (página inicio)
const cardsData = {
    sumSalesToday: 283547000,
    sumActiveProducts: 11702,
    sumActiveUsers: 19598,
}

// La suma de las ventas diarias de los últimos 7 días
const barChartData = [
    {
        day: "Lun",
        sumInMillions: 150,
    },
    {
        day: "Mar",
        sumInMillions: 89,
    },
    {
        day: "Mié",
        sumInMillions: 159,
    },
    {
        day: "Jue",
        sumInMillions: 175,
    },
    {
        day: "Vie",
        sumInMillions: 157,
    },
    {
        day: "Sáb",
        sumInMillions: 172,
    },
    {
        day: "Dom",
        sumInMillions: 174,
    },
];

// Lista con las ventas de las últimas 24 horas, ordenadas por fecha de compra, de las más recientes a las más antiguas
const recentOrders = [
    {
        _id: 20,
        name: "Juan Perez",
        total: 789500,
        date: "2023-05-13T14:52:54.000Z",
    },
    {
        _id: 19,
        name: "María López",
        total: 7525840,
        date: "2023-05-13T13:08:54.000Z",
    },
    {
        _id: 18,
        name: "Ángela Rodríguez",
        total: 5320500,
        date: "2023-05-13T12:52:54.000Z",
    },
    {
        _id: 17,
        name: "Carlos Gómez",
        total: 10547000,
        date: "2023-05-13T10:08:54.000Z",
    },
    {
        _id: 16,
        name: "Diego Soria",
        total: 985500,
        date: "2023-05-13T08:17:54.000Z",
    },
    {
        _id: 15,
        name: "Soledad Ramírez",	
        total: 2684840,
        date: "2023-05-13T07:24:54.000Z",
    },
    {
        _id: 14,
        name: "Rodrigo Pérez",
        total: 4630500,
        date: "2023-05-13T06:33:54.000Z",
    },
    {
        _id: 13,
        name: "Romina Alvarado",
        total: 985000,
        date: "2023-05-13T04:45:54.000Z",
    },
    {
        _id: 12,
        name: "Agustina Alvez",
        total: 850600,
        date: "2023-05-13T02:19:54.000Z",
    },
    {
        _id: 11,
        name: "Lorenzo Benítez",
        total: 1780500,
        date: "2023-05-13T01:24:54.000Z",
    },
    {
        _id: 10,
        name: "María López",
        total: 7525840,
        date: "2023-05-13T00:47:54.000Z",
    },
    {
        _id: 9,
        name: "Ángela Rodríguez",
        total: 5320500,
        date: "2023-05-12T23:30:54.000Z",
    },
    {
        _id: 8,
        name: "Carlos Gómez",
        total: 10547000,
        date: "2023-05-12T23:08:54.000Z",
    },
    {
        _id: 7,
        name: "Diego Soria",
        total: 985500,
        date: "2023-05-12T22:11:54.000Z",
    },
    {   
        _id: 6,
        name: "Soledad Ramírez",
        total: 2684840,
        date: "2023-05-12T20:58:54.000Z",
    },  
    {
        _id: 5,
        name: "Rodrigo Pérez",
        total: 4630500,
        date: "2023-05-12T20:33:54.000Z",
    },
    {
        _id: 4,
        name: "Romina Alvarado",
        total: 985000,
        date: "2023-05-12T20:32:54.000Z",
    },
    {
         _id: 3,
        name: "Agustina Alvez",
        total: 850600,
        date: "2023-05-12T19:54:54.000Z",
    },
    {
        _id: 2,
        name: "Lorenzo Benítez",
        total: 1780500,
        date: "2023-05-12T19:34:54.000Z",
    },
    {
        _id: 1,
        name: "María López",
        total: 7525840,
        date: "2023-05-12T19:20:54.000Z",
    }
];

// Lista de usuarios registrados en la plataforma
const users = [
    {
        "_id":"20",
        "firstname":"Rosa",
        "lastname":"López",
        "calification":0,
        "email":"rosaLopez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T14:51:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"19",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T13:20:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"18",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T12:38:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"17",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T11:49:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"16",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T10:04:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"15",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T09:20:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"14",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T08:27:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"13",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T07:19:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"12",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T06:44:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"11",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T02:30:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"10",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T01:20:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"9",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T23:59:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"8",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T23:44:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"7",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T23:40:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"6",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T22:30:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"5",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:51:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"4",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:25:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"3",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:02:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"2",
        "firstname":"Roxana",
        "lastname":"Martínez",
        "calification":0,
        "email":"roxanaMartinez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T20:23:54.000Z",
        "verified":false,
        "codeverified":982859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"1",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T19:20:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    
];


module.exports = {
    cardsData,
    barChartData,
    recentOrders,
    users,
};